print("In RStudio we don't have cells as in Jupyter, but we can slice up our code using sections Ctrl+Shift+R")
print("The print function and any output generated by our code will be visible in the Console below")
# You can also write directly into the console.
print("The codes can be run by highlighting or standing in a line and pressing Ctrl+Enter")

# In an R file like this, there is no Markdown parts, you can add titles by creating sections, or by using comments


# Variables ---------------------------------------------------------------

# This a section. By using the arrow on the left hand side, I can close this section of the code if I want to.
# You can run a whole section of code by pressing Ctrl+Alt+T

a <- 3  # Variales should be assigned by using this arrow. Alt+- is the hotkey for ti, if you don't feel like typing it
a
a <- a + 1

# You can see all your available variables to the right, on the Environment Tab


b # We get an error message in the console, if our code contains a bug

number_var <- 2
string_var <- "2"

typeof(number_var)
typeof(string_var)

as.numeric(string_var)
as.character(number_var)

false_var <- FALSE 
true_var <- TRUE

a <- 1
b <- 2
c <- 1 + 2
d <- a + b
c == d


# You can find a bunch of useful keyboard shortcuts by pressing Alt+Shift+K

